---
dotfiles_remote_repo: https://github.com/dandyrow/dotfiles.git
dotfiles_local_repo: ~/.dotfiles
dotfiles_pull_single_branch: true
dotfiles_repo_branch: master
dotfiles_target_path: ~/
dotfiles_to_install: []
dotfiles_force_stow: false
